    <h3>Apresenta&ccedil;&atilde;o</h3>
    <p>O presente volume da s&eacute;rie Olhar S&atilde;o Paulo &ndash; <em>Viol&ecirc;ncia e Criminalidade</em> &ndash; apresenta an&aacute;lises in&eacute;ditas relativas ao tema seguran&ccedil;a p&uacute;blica. A rela&ccedil;&atilde;o entre o espa&ccedil;o urbano e o crime foi objeto de v&aacute;rias leituras, que destacaram a sua din&acirc;mica intra-urbana, sempre desigual. Diferente de outras publica&ccedil;&otilde;es recentes que divulgaram o acervo de informa&ccedil;&otilde;es desta Secretaria, as bases de dados utilizadas neste volume prov&ecirc;m de outras secretarias e esferas de governo. O Pro-aim &ndash; Programa de Aprimoramento de Informa&ccedil;&otilde;es sobre Mortalidade, da Secretaria Municipal de Sa&uacute;de, e o Infocrim &ndash; mantido pela Secretaria de Seguran&ccedil;a P&uacute;blica do Estado de S&atilde;o Paulo s&atilde;o exemplos importantes de constru&ccedil;&atilde;o de ferramentas informacionais poderosas, fundamento necess&aacute;rio para o planejamento efetivo da cidade. Sem d&uacute;vida, a crescente qualidade dos dados temcontribu&iacute;do para a redu&ccedil;&atilde;o significativa dos homic&iacute;dios na cidade.<br />
      <br />
  A partir destes importantes bancos de dados, as an&aacute;lises que seguem utilizam metodologias inovadoras de tratamento dos dados estat&iacute;sticos e de sua representa&ccedil;&atilde;o espacial. Neste caminho, articulam-se diferentes unidades espaciais intra-urbanas, como o distrito, o setor censit&aacute;rio e a informa&ccedil;&atilde;o pontual a partir da coordenada geogr&aacute;fica. A multiplicidade de escalas &eacute; entendida como fundamental para a compreens&atilde;o deumacidade das dimens&otilde;es e da complexidade de S&atilde;o Paulo.<br />
  <br />
  Diante do expressivo desafio que constitui hoje superar o fen&ocirc;meno da viol&ecirc;ncia urbana, contamos coma colabora&ccedil;&atilde;o de institui&ccedil;&otilde;es importantes, comnot&aacute;vel produ&ccedil;&atilde;o sobre o tema tanto em &acirc;mbito nacional como estadual e municipal. S&atilde;o elas: Instituto Nacional de Pesquisas Espaciais &ndash; Inpe; Coordenadoria de An&aacute;lise e Planejamento &ndash; CAP, da Secretaria de Seguran&ccedil;a P&uacute;blica do Estado de S&atilde;o Paulo; N&uacute;cleo de Estudos da Viol&ecirc;ncia &ndash; NEV, da Universidade de S&atilde;o Paulo; Instituto S&atilde;o Paulo contra a Viol&ecirc;ncia; e esta pr&oacute;pria Secretaria.<br />
  <br />
  Ao apresentar esta colet&acirc;nea de mapas e an&aacute;lises tem&aacute;ticas, a Secretaria de Planejamento tem por objetivo fomentar uma constru&ccedil;&atilde;o coletiva no sentido de um futuro melhor para a cidade de S&atilde;o Paulo.</p>
    <p><br />
      <strong>Manuelito Pereira Magalh&atilde;es J&uacute;nior</strong><br />
      Secret&aacute;rio Municipal de Planejamento</p>
