<?php include("cabecalho.php"); ?>
<div id="conteudo">
  <h1>Introdu&ccedil;&atilde;o</h1>
  <p>&nbsp;</p>
  <p> Estima-se que, na &eacute;poca da funda&ccedil;&atilde;o de  S&atilde;o Paulo, em 1554, n&atilde;o mais de 100 habitantes viviam nos arredores do col&eacute;gio  erguido pelos padres jesu&iacute;tas, constituindo o n&uacute;cleo inicial da futura cidade.  Nos tr&ecirc;s s&eacute;culos seguintes, o povoado conheceu um lento crescimento, somente  alterado a partir da d&eacute;cada de 1870, quando o primeiro levantamento censit&aacute;rio  realizado no Brasil, em 1872, apontou a presen&ccedil;a de 31.385 moradores. </p>
  <p><br>
    Assim, at&eacute; o final do s&eacute;culo XIX, S&atilde;o  Paulo deixou para tr&aacute;s sua condi&ccedil;&atilde;o de vila afastada dos principais centros  econ&ocirc;micos do pa&iacute;s, sobretudo em raz&atilde;o de sua posi&ccedil;&atilde;o geogr&aacute;fica privilegiada,  entre o porto de Santos e o interior da Prov&iacute;ncia, onde se expandia o cultivo  do caf&eacute;, passando ent&atilde;o a assumir import&acirc;ncia crescente como entreposto  comercial e ponto de entroncamento das rotas pelas quais era exportada a  produ&ccedil;&atilde;o cafeeira.</p>
  <p><br>
    Nesta condi&ccedil;&atilde;o, passou a atrair um volume  expressivo de trabalhadores e a fixar uma parcela significativa do fluxo de  imigrantes europeus direcionado, inicialmente, para substituir a m&atilde;o-de-obra  escrava na lavoura cafeeira. Muitos desses imigrantes acabavam permanecendo na  capital ou a ela retornavam ap&oacute;s algum tempo.</p>
  <p><br>
    Este fluxo imigrat&oacute;rio perdurou nas duas primeiras  d&eacute;cadas do s&eacute;culo XX, o que manteve a cidade em elevado ritmo de crescimento  demogr&aacute;fico. Durante este per&iacute;odo, criaram-se as bases para o desenvolvimento  industrial de S&atilde;o Paulo, com a transfer&ecirc;ncia de capitais gerados na atividade agr&aacute;ria  para as incipientes ind&uacute;strias locais.</p>
  <p><br>
    A transforma&ccedil;&atilde;o de S&atilde;o Paulo em importante centro  industrial deu-se progressivamente, mas j&aacute; era plenamente vis&iacute;vel na d&eacute;cada de  1920 &minus; as manifesta&ccedil;&otilde;es art&iacute;sticas do grupo Modernista em 1922 refletem bem este  fato. O processo de industrializa&ccedil;&atilde;o no Brasil, centrado em S&atilde;o Paulo, muito  beneficiou-se de dois eventos hist&oacute;ricos de grande import&acirc;ncia: a 1&ordf; e a 2&ordf;  Guerras Mundiais, respectivamente ocorridas de 1914 a 1918 e de 1939 a 1945,  per&iacute;odos em que a retra&ccedil;&atilde;o do com&eacute;rcio mundial gerou a necessidade de  substitui&ccedil;&atilde;o de importa&ccedil;&otilde;es, favorecendo a produ&ccedil;&atilde;o local de bens de consumo.</p>
  <p><br>
    Por volta de 1950, j&aacute; com os fluxos de  imigra&ccedil;&atilde;o estrangeira bastante reduzidos e, ao mesmo tempo, em fase de grande  impulso industrial, a cidade passou a atrair contingentes populacionais de outros  Estados do Brasil, transformando-se ent&atilde;o no maior p&oacute;lo de migra&ccedil;&atilde;o interna.  Foram mais de 3 milh&otilde;es de pessoas &ndash; trabalhadores e suas fam&iacute;lias &ndash; que aqui  chegaram&nbsp; entre 1950 e 1980 e este  processo, aliado ao crescimento vegetativo da popula&ccedil;&atilde;o, manteve as altas taxas  de crescimento da cidade no per&iacute;odo (entre 4% e 5% ao ano).</p>
  <p><br>
    Este quadro &eacute; bastante alterado, entretanto,  a partir da d&eacute;cada de 80, em decorr&ecirc;ncia tanto do processo de desconcentra&ccedil;&atilde;o  industrial, que afetou a cidade a partir de meados dos anos 70 e redirecionou  parte de suas instala&ccedil;&otilde;es industriais para outras regi&otilde;es do Estado de S&atilde;o  Paulo e do pa&iacute;s, quanto do processo de moderniza&ccedil;&atilde;o tecnol&oacute;gica e gerencial,  que suprimiu empregos no setor secund&aacute;rio da economia. A cidade teve ent&atilde;o reduzido  seu poder de atra&ccedil;&atilde;o populacional, passando a apresentar saldos migrat&oacute;rios  negativos. Ainda na d&eacute;cada de 80, o crescimento vegetativo tamb&eacute;m sofreu um  arrefecimento, em decorr&ecirc;ncia da diminui&ccedil;&atilde;o dos &iacute;ndices de fertilidade e de natalidade  na popula&ccedil;&atilde;o brasileira. </p>
  <p><br>
    Tudo isso contribuiu para a redu&ccedil;&atilde;o acentuada  da taxa de crescimento demogr&aacute;fico para patamares muito menores que aqueles  apresentados nos 100 anos anteriores, chegando a &iacute;ndices em torno de 1,2% ao  ano. Em outras palavras, se a aglomera&ccedil;&atilde;o urbana continuou a crescer em seu  conjunto, isto deveu-se &agrave; expans&atilde;o das &aacute;reas perif&eacute;ricas do munic&iacute;pio de S&atilde;o  Paulo (incluindo aquelas situadas em zonas de prote&ccedil;&atilde;o a mananciais) e ao  crescimento que ainda se observa em grande parte dos munic&iacute;pios da sua regi&atilde;o  metropolitana.</p>
  <p><br>
  Esta nova din&acirc;mica intensificou-se de tal  forma que, desde a d&eacute;cada de 90, o aumento populacional da cidade tem-se  pautado por um lento crescimento vegetativo, aliado a saldos migrat&oacute;rios totais  negativos &minus; &eacute; maior o n&uacute;mero de pessoas que se mudam para fora de S&atilde;o Paulo do  que as que v&ecirc;m para aqui se estabelecer &minus;, o que resulta em taxas m&eacute;dias de  crescimento menores que 1% ao ano.</p>
  <p><br>
    S&atilde;o Paulo, maior cidade do Brasil desde a  d&eacute;cada de 60, &eacute; hoje o mais poderoso p&oacute;lo de atividades terci&aacute;rias do pa&iacute;s e  sua popula&ccedil;&atilde;o se aproxima da cifra dos 11 milh&otilde;es de habitantes, distribu&iacute;dos  pelos 1.509 km2 &nbsp;de seu  munic&iacute;pio, que se divide em 31 subprefeituras e estas, em 96 distritos. S&atilde;o  Paulo tamb&eacute;m &eacute; o centro da regi&atilde;o metropolitana de mesmo nome, que, com seus 19  milh&otilde;es de habitantes, ocupa a 4&ordf; posi&ccedil;&atilde;o no <em>ranking </em>das&nbsp; maiores  aglomera&ccedil;&otilde;es urbanas do mundo. S&atilde;o 39 munic&iacute;pios, incluindo o da capital,  8.051km2 e uma mancha urbana cont&iacute;nua que, no sentido leste-oeste,  apresenta cerca de 100 km de extens&atilde;o.</p>
  <p><br>
    A popula&ccedil;&atilde;o de S&atilde;o Paulo apresenta  algumas especificidades em termos demogr&aacute;ficos e urbanos, entre as quais  merecem destaque certos aspectos de g&ecirc;nero e idade, assim como de sua  distribui&ccedil;&atilde;o territorial.</p>
  <p><br>
    De fato, seguindo o padr&atilde;o encontrado em  grandes &aacute;reas urbanas, a popula&ccedil;&atilde;o do munic&iacute;pio de S&atilde;o Paulo vem sofrendo um  processo de &ldquo;feminiliza&ccedil;&atilde;o&rdquo;, ou seja, ao longo dos anos tem sido crescente a  predomin&acirc;ncia num&eacute;rica de mulheres no conjunto da popula&ccedil;&atilde;o. Dados do Censo de  1980 indicam, naquela data, uma propor&ccedil;&atilde;o de 96 homens para cada 100 mulheres  residentes no munic&iacute;pio. Em 2000, essa rela&ccedil;&atilde;o j&aacute; era de 91 para 100 e  estima-se que, atualmente, esteja em torno de 90, ou seja, existem 9 homens  para cada 10 mulheres na cidade. Vale ressaltar que esta &ldquo;raz&atilde;o entre os sexos&rdquo;  varia em fun&ccedil;&atilde;o dos grupos et&aacute;rios, sendo mais discrepante nas idades mais  avan&ccedil;adas: a partir dos 60 anos, em raz&atilde;o da longevidade feminina, a propor&ccedil;&atilde;o  encontrada &eacute; de 6,8 homens para cada 10 mulheres.<br>
    Simultaneamente ao fen&ocirc;meno de &ldquo;feminiliza&ccedil;&atilde;o&rdquo;,  verifica-se a ocorr&ecirc;ncia de um processo de &ldquo;envelhecimento&rdquo; desta mesma  popula&ccedil;&atilde;o, que se traduz na redu&ccedil;&atilde;o da participa&ccedil;&atilde;o de grupos et&aacute;rios mais  jovens em rela&ccedil;&atilde;o aos adultos e velhos. Em 1980, o grupo de 0 a 14 anos de  idade representava 30% do total de residentes e, 20 anos depois, esta  participa&ccedil;&atilde;o caiu para 25%, apontando uma tend&ecirc;ncia que deve se intensificar  nas pr&oacute;ximas d&eacute;cadas. Inversamente, a faixa et&aacute;ria de 60 anos e mais, que em  1980 correspondia a 6% da popula&ccedil;&atilde;o, teve sua representatividade aumentada para  mais de 9% em 2000. </p>
  <p><br>
    O &ldquo;&iacute;ndice de envelhecimento&rdquo; &eacute; um  indicador importante, uma vez que estabelece a propor&ccedil;&atilde;o de idosos em rela&ccedil;&atilde;o  ao total de crian&ccedil;as numa determinada popula&ccedil;&atilde;o. Na cidade de S&atilde;o Paulo, em  1991, havia em m&eacute;dia 18 idosos para cada grupo de 100 crian&ccedil;as, aumentando para  25 por 100 em 2000. Esta propor&ccedil;&atilde;o varia em fun&ccedil;&atilde;o tanto do sexo (&eacute; sempre  maior no caso das mulheres) como da localiza&ccedil;&atilde;o da popula&ccedil;&atilde;o na cidade &minus; &eacute; mais  elevada em regi&otilde;es de urbaniza&ccedil;&atilde;o consolidada do que em &aacute;reas perif&eacute;ricas,  justamente devido &agrave; maior presen&ccedil;a de crian&ccedil;as nessas regi&otilde;es. Credita-se o  processo de envelhecimento, sobretudo, &agrave; queda de fecundidade, j&aacute; apontada, e  aos progressos da medicina preventiva e curativa que, pela expans&atilde;o dos  servi&ccedil;os de sa&uacute;de, acabaram por aumentar a expectativa de vida da popula&ccedil;&atilde;o.<br>
    Um outro importante processo a ser  destacado refere-se a altera&ccedil;&otilde;es na din&acirc;mica de ocupa&ccedil;&atilde;o urbana e de  distribui&ccedil;&atilde;o da popula&ccedil;&atilde;o no territ&oacute;rio municipal. At&eacute; a d&eacute;cada de 80, todas as  regi&otilde;es da cidade apresentavam crescimento positivo, com exce&ccedil;&atilde;o de um n&uacute;cleo  muito central formado pelos distritos de Bel&eacute;m, Bom Retiro, Br&aacute;s e Pari. A  partir de ent&atilde;o, a tend&ecirc;ncia &agrave; redu&ccedil;&atilde;o do n&uacute;mero de habitantes espraiou-se para  &aacute;reas adjacentes, fazendo com que o n&uacute;cleo central e outros distritos de  ocupa&ccedil;&atilde;o j&aacute; consolidada viessem a apresentar taxas negativas de crescimento,  incluindo &aacute;reas da zona leste mais pr&oacute;ximas ao centro da cidade e partes das  regi&otilde;es norte, oeste e sul, formando uma mancha em cont&iacute;nua expans&atilde;o.</p>
  <p><br>
    Durante a d&eacute;cada de 90, esse processo  intensificou-se, num&eacute;rica e espacialmente, quando aproximadamente 60% dos  distritos do munic&iacute;pio passaram a apresentar perda populacional. Neste per&iacute;odo,  o conjunto de distritos que continuaram a registrar crescimento positivo foram  aqueles situados nas &aacute;reas mais extremas da cidade, a maior parte lim&iacute;trofes  com outros munic&iacute;pios da regi&atilde;o metropolitana, indicando que o processo de  periferiza&ccedil;&atilde;o ultrapassou os limites de S&atilde;o Paulo, em dire&ccedil;&atilde;o &agrave;s cidades de seu  entorno.<br>
    Entre os fatores que certamente  contribu&iacute;ram para este espraiamento da ocupa&ccedil;&atilde;o urbana e para a mudan&ccedil;a no  padr&atilde;o de crescimento demogr&aacute;fico no munic&iacute;pio, merecem destaque: a  continuidade do processo de desconcentra&ccedil;&atilde;o industrial em dire&ccedil;&atilde;o a outros  munic&iacute;pios da Regi&atilde;o Metropolitana de S&atilde;o Paulo e interior do Estado; o alto  custo de vida na capital (sobretudo no que se refere &agrave; habita&ccedil;&atilde;o); e a expans&atilde;o  de atividades terci&aacute;rias nas &aacute;reas mais consolidadas do centro urbano, substituindo  o uso residencial de muitas &aacute;reas pelo uso comercial e de servi&ccedil;os.</p>
  <p><br>
    As tr&ecirc;s caracter&iacute;sticas citadas anteriormente  &ndash; feminiliza&ccedil;&atilde;o, envelhecimento e periferiza&ccedil;&atilde;o da popula&ccedil;&atilde;o &ndash; merecem aten&ccedil;&atilde;o  especial de todos aqueles que se dedicam &agrave; formula&ccedil;&atilde;o de pol&iacute;ticas p&uacute;blicas,  pois, a m&eacute;dio e longo prazos, ter&atilde;o import&acirc;ncia decisiva na defini&ccedil;&atilde;o do perfil  e distribui&ccedil;&atilde;o dos habitantes de nossa cidade.</p>
</div><?php include("rodape.php"); ?>